rateslib/curves.py
tests/test_curves.py

Hi,
- I needed to add an if statement with isinstance to the Curve Class constructor given if the interpolation method that is passed is custom, if I wanted to make the interpolation str lower case.
- I added error handling to the interpolate function, including highlighting the argument that was passed.
- Added tests to test_curves.py.

 ENH: Interpolation Error Handling #37

---

docs/source/f_fxr.rst
docs/source/i_get_started.rst
docs/source/i_guide.rst

Of course, I can squash if you want.

Some minor spelling changes to the docs

---

rateslib/curves.py
tests/test_curves.py

Added a case where it checks whether the nodes dict is sorted or not in reference to #120

Added ValueError for not sorted dicts

---

docs/source/i_whatsnew.rst
python/rateslib/legs.py
tests/test_instruments.py

BUG: don't allow initialising `ZCS` with freq of 'Z'

---

docs/source/i_whatsnew.rst
python/rateslib/instruments.py
tests/test_instruments_bonds.py

BUG: `FixedRateBond.rate` now unaffected by `fx` and `base`.

---

Cargo.toml
python/rateslib/__init__.py
python/rateslib/default.py
python/rateslib/fxdev/__init__.py
python/rateslib/json.py
src/dual/dual_py.rs
src/fx/rates.rs
src/fx/rates_py.rs
src/json/json_py.rs
tests/test_calendarsrs.py
tests/test_fxrs.py

This PR alters the way JSON in Python handles objects that are Python wrappers for the Rust struct.
It also develops the FXRates in Rust that is yet to be put into production.

REF: JSON refactor and FXRates rust struct definition change

---

python/rateslib/dual/__init__.py
src/dual/dual1.rs
src/dual/dual2.rs
src/dual/dual_py.rs
src/fx/rates.rs
src/fx/rates_py.rs

Improvement for Dual into Dual2
For 100 variables:  Before: 22 us, After: 3 us
For 1 variable: Before 1.5us, After 0.5us

PERF: impl Into for Duals 

---

docs/source/i_whatsnew.rst
python/rateslib/instruments.py
python/tests/test_instruments_bonds.py

BUG: spec push fails comparison on some objects

---

docs/source/i_whatsnew.rst
python/rateslib/instruments.py
python/tests/test_instruments.py

BUG: `index_base` forecasting in the past with "monthly" `index_method`

---

.gitignore

BUG: fix spelling in .gitignore

---

Cargo.toml
rust/calendars/calendar.rs
rust/calendars/calendar_py.rs
rust/curves/curve_py.rs
rust/dual/dual_py.rs
rust/dual/enums.rs

Minimal, unformatted, implementation to upgrade to pyo3, compiling locally without errors.

UPG: rust packages upgrades

---

rust/dual/dual_ops/pow.rs

PERF: dual power operation avoid unnecessary dual clones and reshuffles

---

rust/scheduling/calendars/named/all.rs
rust/scheduling/calendars/named/bus.rs
rust/scheduling/calendars/named/fed.rs
rust/scheduling/calendars/named/ldn.rs
rust/scheduling/calendars/named/mod.rs
rust/scheduling/calendars/named/mum.rs
rust/scheduling/calendars/named/nyc.rs
rust/scheduling/calendars/named/osl.rs
rust/scheduling/calendars/named/stk.rs
rust/scheduling/calendars/named/syd.rs
rust/scheduling/calendars/named/tgt.rs
rust/scheduling/calendars/named/tro.rs
rust/scheduling/calendars/named/tyo.rs
rust/scheduling/calendars/named/wlg.rs
rust/scheduling/calendars/named/zur.rs
rust/scheduling/calendars/named_cal.rs
rust/scheduling/enums.rs
rust/scheduling/mod.rs

(cherry picked from commit c41d73f7a9b7fb35b24714cd889387931c442f1e)

CI: rust fix

---

rust/scheduling/calendars/dateroll.rs
rust/scheduling/frequency/frequency.rs
rust/scheduling/frequency/rollday.rs
rust/scheduling/py/calendar.rs

(cherry picked from commit d652e6c15d1053b2275cb65880ae3a0f63e94903)

ENH: RollDay `uadd` and refactors

---

rust/scheduling/py/calendar.rs

(cherry picked from commit 6babbf0f86a136db5d5155ca19e6aedf25dcd4b1)

REF: remove state setting rom Python pickle (#27)

---

python/rateslib/calendars/rs.py
python/rateslib/rs.pyi
python/rateslib/scheduling/scheduling.py
python/rateslib/scheduling/wrappers.py
python/rateslib/typing.py
python/tests/scheduling/test_frequency.py
python/tests/scheduling/test_py_wrapper.py
python/tests/scheduling/test_schedule.py
rust/scheduling/calendars/dateroll.rs
rust/scheduling/frequency/frequency.rs
rust/scheduling/py/adjuster.rs
rust/scheduling/py/frequency.rs
rust/scheduling/py/mod.rs
rust/scheduling/py/rollday.rs
rust/scheduling/py/schedule.rs
rust/scheduling/schedule.rs

(cherry picked from commit b47dba48f4f9fa9e8f2f0f0d77d6004fb764bd2a)

REF: move `Schedule` to Rust implementation

---

python/rateslib/solver.py
python/tests/test_solver.py

(cherry picked from commit 4cafa88cca6e45e1eb4c114bc1b3d2f989cc0a35)

BUG: solver ad order for composite curve types (#34)

---

python/rateslib/instruments/generics.py
python/tests/test_instruments.py

(cherry picked from commit 98c5a97bbe4ed8065672b4fda5f47c1bb6492a8f)

ENH: add `o/n_rate` to `Value` (#35)

---

python/rateslib/curves/curves.py
python/rateslib/instruments/bonds/securities.py
python/rateslib/instruments/generics.py
python/rateslib/legs/base.py
python/rateslib/legs/index.py
python/rateslib/legs/mtm.py
python/rateslib/periods/index.py
rust/scheduling/frequency/frequency.rs

(cherry picked from commit b40c25775abfbae1d5ad9333e5fc094f8ba98598)

CLN: fix doc tests (#38)

---

python/rateslib/__init__.py
python/rateslib/scheduling/__init__.py
python/rateslib/scheduling/wrappers.py

(cherry picked from commit 1059095d7daf46444cfc8bdeb67dc4dedbdee27f)

BUG: namespace for Scheduling objs (#47)

---

python/rateslib/__init__.py
python/rateslib/dual/__init__.py
python/tests/scheduling/test_schedule.py
python/tests/serialization/test_json.py
python/tests/serialization/test_pickle.py
python/tests/test_dualrs.py
rust/json/json_py.rs
rust/scheduling/py/imm.rs
rust/scheduling/py/schedule.rs
rust/scheduling/schedule.rs
rust/scheduling/serde.rs

(cherry picked from commit dd6d5f8accc07bee3f45941a33425affca23632d)

ENH: add Imm pickling (#52)

---

python/tests/test_instruments_bonds.py

(cherry picked from commit cb5c6484e5647864041a68a1dced73ecd634ea40)

TST: repo calcs (#54)

---

python/rateslib/__init__.py
python/rateslib/scheduling/__init__.py
python/tests/serialization/test_pickle.py
rust/scheduling/py/adjuster.rs

(cherry picked from commit 99e2fe1e4ff5871fe67a29f31ccb6de57d086eee)

REF: pickle for `PyAdjuster` (#63)

---

python/rateslib/scheduling/__init__.py
rust/scheduling/frequency/mod.rs
rust/scheduling/frequency/rollday.rs
rust/scheduling/mod.rs
rust/scheduling/py/adjuster.rs

(cherry picked from commit 0e9ba85dab0c35ae6f60307e128731a706c9e34e)

REF: move `get_roll` (#64)

---

python/rateslib/scheduling/__init__.py
python/tests/serialization/test_pickle.py
rust/scheduling/py/frequency.rs

(cherry picked from commit afbc536e90c3b46a67bc1dd11fb0ef2eb7732c55)

REF: add pickle to `Frequency`. (#65)

---

python/tests/serialization/test_json.py
python/tests/serialization/test_repr.py
rust/json/json_py.rs
rust/json/mod.rs
rust/scheduling/frequency/imm.rs
rust/scheduling/py/calendar.rs
rust/scheduling/py/imm.rs
rust/scheduling/py/schedule.rs

(cherry picked from commit 3673a35d69425643fadd2c2af485643b2cc69908)

ENH: add serialization to scheduling Enums (#68)

---

python/tests/serialization/test_json.py
python/tests/serialization/test_pickle.py
python/tests/serialization/test_repr.py
rust/json/json_py.rs
rust/scheduling/frequency/frequency.rs
rust/scheduling/py/frequency.rs

(cherry picked from commit 040921e81d026bdc8459f192f47db5f2365845de)

ENH: serialize `Frequency` (#70)

---

python/rateslib/_deprecations_record.txt
python/rateslib/scheduling/imm.py
python/tests/scheduling/test_calendars.py

(cherry picked from commit d9586b846a96c3a951c5e30b9a3d5a44a1b55c3a)

DEPR: Imm `definition` inputs to get and next (#80)

---

python/rateslib/scheduling/dcfs.py

(cherry picked from commit 25a8c159083e3a1f7a5f03053a2b06f570c37d47)

PERF: simple py-only dcf (#95)

---

python/rateslib/__init__.py
python/rateslib/instruments/bonds/securities.py
python/rateslib/instruments/rates/multi_currency.py
python/rateslib/instruments/utils.py
python/rateslib/legs/__init__.py
python/rateslib/legs/base.py
python/rateslib/legs/index.py
python/rateslib/legs/mtm.py
python/rateslib/legs/zeros.py
python/tests/scheduling/test_frequency.py
python/tests/test_instruments.py
python/tests/test_legs.py

(cherry picked from commit eecf3f59e47f042a570b1a8b77c08de5cacf504c)

ENH: custom Amortization (#97)

---

python/rateslib/instruments/bonds/securities.py
python/rateslib/instruments/rates/single_currency.py
python/rateslib/legs/index.py
python/rateslib/legs/zeros.py
python/rateslib/periods/base.py
python/rateslib/periods/cashflow.py
python/rateslib/periods/credit.py
python/rateslib/periods/index.py
python/rateslib/periods/rates.py
python/tests/test_instruments_bonds.py
python/tests/test_legs.py
python/tests/test_periods.py

(cherry picked from commit 2574b70c7ff7bfd4c28dabf92658cff6a280d614)

REF: make all `cashflow` method not property as ABC method (#106)

---

python/rateslib/curves/curves.py
python/rateslib/default.py
python/rateslib/instruments/bonds/securities.py
python/rateslib/instruments/generics.py
python/rateslib/instruments/rates/inflation.py
python/rateslib/legs/index.py
python/rateslib/periods/index.py
python/rateslib/periods/utils.py
python/rateslib/typing.py
python/tests/test_curves.py

(cherry picked from commit 4c34e34c96749123e560a67e4a7282090242667c)

REF: add a Python Result type (#116)

---

python/rateslib/__init__.py
python/rateslib/periods/cashflow.py

Co-authored-by: Mike Lync <mikelync@users.noreply.github.com>
Co-authored-by: JHM Darbyshire (M1) <attack68@users.noreply.github.com>
(cherry picked from commit 465cf3ffb7bdc79566c1317044c2d41d1f903a0c)

DOC: clean and get running (#117)

---

python/rateslib/periods/__init__.py
python/rateslib/periods/components/credit.py
python/rateslib/periods/components/float_period.py
python/rateslib/periods/components/float_rate.py
python/rateslib/periods/components/fx_volatility.py
python/rateslib/periods/components/protocols/npv.py
python/rateslib/periods/components/utils.py
python/tests/periods/test_periods_init.py
python/tests/periods/test_periods_legacy.py

(cherry picked from commit b80fc80428a39e884c6f4d54f65177934397e2b6)

REF: add `_screen_forward_and_ex_div` for post adjustment of NPV (#127)

---

python/rateslib/data/fixings.py
python/rateslib/enums/generics.py
python/rateslib/errors.py
python/rateslib/periods/components/__init__.py
python/rateslib/periods/components/base_period.py
python/rateslib/periods/components/cashflow.py
python/rateslib/periods/components/parameters/__init__.py
python/rateslib/periods/components/parameters/fx_volatility.py
python/rateslib/periods/components/parameters/mtm.py
python/rateslib/periods/components/parameters/settlement.py
python/rateslib/periods/components/protocols/cashflows.py
python/rateslib/periods/components/protocols/npv.py
python/rateslib/typing.py
python/tests/periods/test_periods_init.py
python/tests/periods/test_periods_legacy.py

(cherry picked from commit 35d4c4faf8ca324497a53958e04484493c3287ed)

ENH: add `MtmCashflow` component (#128)

---

python/rateslib/fx_volatility/delta_vol.py
python/rateslib/fx_volatility/sabr.py
python/rateslib/instruments/fx_volatility/vanilla.py
python/rateslib/periods/fx_volatility.py
python/tests/test_fx_volatility.py

Co-authored-by: Mike Lync <mikelync@users.noreply.github.com>
(cherry picked from commit 122a11621a48a7505a2c6783bd4e0f743f22f3c4)

REF: getfromstrike arg changes (#129)
